# Generated by Django 4.2.6 on 2023-10-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('available', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'calendar',
                'managed': False,
            },
        ),
    ]
