# Generated by Django 4.2.6 on 2023-10-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allcolor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('string_field_0', models.CharField(max_length=255)),
                ('string_field_2', models.CharField(max_length=255)),
                ('string_field_3', models.CharField(max_length=255)),
                ('string_field_4', models.CharField(max_length=255)),
                ('string_field_5', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'allcolor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryCt',
            fields=[
                ('unnamed_0', models.CharField(db_column='Unnamed: 0', max_length=255, primary_key=True, serialize=False)),
                ('on_hand', models.IntegerField(db_column='On Hand')),
            ],
            options={
                'db_table': 'inventory_ct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ord1',
            fields=[
                ('item', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('pcs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ord1',
                'managed': False,
            },
        ),
    ]
