# Generated by Django 4.2.7 on 2023-11-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allcolor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ct1', models.CharField(blank=True, max_length=50, null=True)),
                ('ct2', models.CharField(blank=True, max_length=50, null=True)),
                ('ct3', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'allcolor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('item', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pcs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calendar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtAc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unnamed_0', models.CharField(db_column='Unnamed: 0', max_length=50)),
                ('on_hand', models.FloatField(blank=True, db_column='On Hand', null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('color_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ct1', models.CharField(blank=True, max_length=50, null=True)),
                ('ct2', models.CharField(blank=True, max_length=50, null=True)),
                ('ct3', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ct_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtRoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ny', models.IntegerField(blank=True, null=True)),
                ('nj4_2', models.IntegerField(blank=True, null=True)),
                ('ct', models.IntegerField(blank=True, null=True)),
                ('pa1_7', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('on_hand', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ct_room_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cw2Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avgg', models.FloatField(blank=True, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('o305', models.IntegerField(blank=True, null=True)),
                ('o306', models.IntegerField(blank=True, null=True)),
                ('o307', models.IntegerField(blank=True, null=True)),
                ('o308', models.IntegerField(blank=True, null=True)),
                ('o309', models.IntegerField(blank=True, null=True)),
                ('o342', models.IntegerField(blank=True, null=True)),
                ('o344', models.IntegerField(blank=True, null=True)),
                ('o346', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cw2_order_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cw2OrderData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avgg', models.FloatField(blank=True, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('o305', models.IntegerField(blank=True, null=True)),
                ('o306', models.IntegerField(blank=True, null=True)),
                ('o307', models.IntegerField(blank=True, null=True)),
                ('o308', models.IntegerField(blank=True, null=True)),
                ('o309', models.IntegerField(blank=True, null=True)),
                ('o342', models.IntegerField(blank=True, null=True)),
                ('o344', models.IntegerField(blank=True, null=True)),
                ('o346', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cw2_order_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryCt',
            fields=[
                ('unnamed_0', models.CharField(db_column='Unnamed: 0', max_length=50, primary_key=True, serialize=False)),
                ('item_description', models.CharField(blank=True, db_column='Item Description', max_length=50, null=True)),
                ('reorder_pt_min_field', models.CharField(blank=True, db_column='Reorder Pt (Min)', max_length=50, null=True)),
                ('max', models.CharField(blank=True, max_length=50, null=True)),
                ('on_hand', models.FloatField(blank=True, db_column='On Hand', null=True)),
                ('on_sales_order', models.FloatField(blank=True, db_column='On Sales Order', null=True)),
                ('for_assemblies', models.FloatField(blank=True, db_column='For Assemblies', null=True)),
                ('available', models.FloatField(blank=True, null=True)),
                ('order', models.CharField(blank=True, db_column='Order', max_length=50, null=True)),
                ('on_po', models.FloatField(blank=True, db_column='On PO', null=True)),
                ('reorder_qty', models.FloatField(blank=True, db_column='Reorder Qty', null=True)),
                ('next_deliv', models.CharField(blank=True, db_column='Next Deliv', max_length=50, null=True)),
                ('sales_week', models.FloatField(blank=True, db_column='Sales/Week', null=True)),
            ],
            options={
                'db_table': 'inventory_ct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryMiller',
            fields=[
                ('unnamed_0', models.CharField(db_column='Unnamed: 0', max_length=50, primary_key=True, serialize=False)),
                ('item_description', models.CharField(blank=True, db_column='Item Description', max_length=50, null=True)),
                ('reorder_pt_min_field', models.CharField(blank=True, db_column='Reorder Pt (Min)', max_length=50, null=True)),
                ('max', models.CharField(blank=True, max_length=50, null=True)),
                ('on_hand', models.FloatField(blank=True, db_column='On Hand', null=True)),
                ('on_sales_order', models.FloatField(blank=True, db_column='On Sales Order', null=True)),
                ('for_assemblies', models.FloatField(blank=True, db_column='For Assemblies', null=True)),
                ('available', models.FloatField(blank=True, null=True)),
                ('order', models.CharField(blank=True, db_column='Order', max_length=50, null=True)),
                ('on_po', models.FloatField(blank=True, db_column='On PO', null=True)),
                ('reorder_qty', models.FloatField(blank=True, db_column='Reorder Qty', null=True)),
                ('next_deliv', models.CharField(blank=True, db_column='Next Deliv', max_length=50, null=True)),
                ('sales_week', models.FloatField(blank=True, db_column='Sales/Week', null=True)),
            ],
            options={
                'db_table': 'inventory_miller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryNj',
            fields=[
                ('unnamed_0', models.CharField(db_column='Unnamed: 0', max_length=50, primary_key=True, serialize=False)),
                ('item_description', models.CharField(blank=True, db_column='Item Description', max_length=50, null=True)),
                ('reorder_pt_min_field', models.FloatField(blank=True, db_column='Reorder Pt (Min)', null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('on_hand', models.FloatField(blank=True, db_column='On Hand', null=True)),
                ('on_sales_order', models.FloatField(blank=True, db_column='On Sales Order', null=True)),
                ('for_assemblies', models.FloatField(blank=True, db_column='For Assemblies', null=True)),
                ('available', models.FloatField(blank=True, null=True)),
                ('order', models.CharField(blank=True, db_column='Order', max_length=50, null=True)),
                ('on_po', models.FloatField(blank=True, db_column='On PO', null=True)),
                ('reorder_qty', models.FloatField(blank=True, db_column='Reorder Qty', null=True)),
                ('next_deliv', models.CharField(blank=True, db_column='Next Deliv', max_length=50, null=True)),
                ('sales_week', models.FloatField(blank=True, db_column='Sales/Week', null=True)),
            ],
            options={
                'db_table': 'inventory_nj',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryNy',
            fields=[
                ('unnamed_0', models.CharField(db_column='Unnamed: 0', max_length=50, primary_key=True, serialize=False)),
                ('item_description', models.CharField(blank=True, db_column='Item Description', max_length=50, null=True)),
                ('reorder_pt_min_field', models.CharField(blank=True, db_column='Reorder Pt (Min)', max_length=50, null=True)),
                ('max', models.CharField(blank=True, max_length=50, null=True)),
                ('on_hand', models.FloatField(blank=True, db_column='On Hand', null=True)),
                ('on_sales_order', models.FloatField(blank=True, db_column='On Sales Order', null=True)),
                ('for_assemblies', models.FloatField(blank=True, db_column='For Assemblies', null=True)),
                ('available', models.FloatField(blank=True, null=True)),
                ('order', models.CharField(blank=True, db_column='Order', max_length=50, null=True)),
                ('on_po', models.FloatField(blank=True, db_column='On PO', null=True)),
                ('reorder_qty', models.FloatField(blank=True, db_column='Reorder Qty', null=True)),
                ('next_deliv', models.CharField(blank=True, db_column='Next Deliv', max_length=50, null=True)),
                ('sales_week', models.FloatField(blank=True, db_column='Sales/Week', null=True)),
            ],
            options={
                'db_table': 'inventory_ny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryPa',
            fields=[
                ('unnamed_0', models.CharField(db_column='Unnamed: 0', max_length=50, primary_key=True, serialize=False)),
                ('item_description', models.CharField(blank=True, db_column='Item Description', max_length=50, null=True)),
                ('reorder_pt_min_field', models.CharField(blank=True, db_column='Reorder Pt (Min)', max_length=50, null=True)),
                ('max', models.CharField(blank=True, max_length=50, null=True)),
                ('on_hand', models.FloatField(blank=True, db_column='On Hand', null=True)),
                ('on_sales_order', models.FloatField(blank=True, db_column='On Sales Order', null=True)),
                ('for_assemblies', models.FloatField(blank=True, db_column='For Assemblies', null=True)),
                ('available', models.FloatField(blank=True, null=True)),
                ('order', models.CharField(blank=True, db_column='Order', max_length=50, null=True)),
                ('on_po', models.FloatField(blank=True, db_column='On PO', null=True)),
                ('reorder_qty', models.FloatField(blank=True, db_column='Reorder Qty', null=True)),
                ('next_deliv', models.CharField(blank=True, db_column='Next Deliv', max_length=50, null=True)),
                ('sales_week', models.FloatField(blank=True, db_column='Sales/Week', null=True)),
            ],
            options={
                'db_table': 'inventory_pa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ord2',
            fields=[
                ('item', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pcs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ord2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ord2Ac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('color_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ord2_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ord3',
            fields=[
                ('item', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pcs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ord3',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ord3Ac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('color_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ord3_ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Po300',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'po300',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Po301',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'po301',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomCw2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ny', models.IntegerField(blank=True, null=True)),
                ('nj13', models.IntegerField(blank=True, null=True)),
                ('pa7', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_cw2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomE2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ny', models.IntegerField(blank=True, null=True)),
                ('nj9', models.IntegerField(blank=True, null=True)),
                ('ct', models.IntegerField(blank=True, null=True)),
                ('pa5', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_e2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomMs',
            fields=[
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ny', models.IntegerField(blank=True, null=True)),
                ('nj4_2', models.IntegerField(blank=True, null=True)),
                ('ct', models.IntegerField(blank=True, null=True)),
                ('pa1_7', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'room_ms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomSe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ny', models.IntegerField(blank=True, null=True)),
                ('nj6_5', models.IntegerField(blank=True, null=True)),
                ('ct', models.IntegerField(blank=True, null=True)),
                ('pa4_2', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_se',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomSg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ny', models.IntegerField(blank=True, null=True)),
                ('nj3_5', models.IntegerField(blank=True, null=True)),
                ('ct', models.IntegerField(blank=True, null=True)),
                ('pa3_5', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_sg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbm', models.FloatField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('ny', models.IntegerField(blank=True, null=True)),
                ('nj4_2', models.IntegerField(blank=True, null=True)),
                ('ct', models.IntegerField(blank=True, null=True)),
                ('pa1_7', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(blank=True, null=True)),
                ('on_hand', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'room_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.CharField(blank=True, max_length=50, null=True)),
                ('item_description', models.CharField(blank=True, db_column='Item Description', max_length=50, null=True)),
                ('reorder_pt_min_field', models.CharField(blank=True, db_column='Reorder Pt (Min)', max_length=50, null=True)),
                ('max', models.CharField(blank=True, max_length=50, null=True)),
                ('on_hand', models.IntegerField(blank=True, db_column='On Hand', null=True)),
                ('on_sales_order', models.IntegerField(blank=True, db_column='On Sales Order', null=True)),
                ('for_assemblies', models.IntegerField(blank=True, db_column='For Assemblies', null=True)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('order', models.CharField(blank=True, db_column='Order', max_length=50, null=True)),
                ('on_po', models.IntegerField(blank=True, db_column='On PO', null=True)),
                ('reorder_qty', models.IntegerField(blank=True, db_column='Reorder Qty', null=True)),
                ('next_deliv', models.CharField(blank=True, db_column='Next Deliv', max_length=50, null=True)),
                ('sales_week', models.IntegerField(blank=True, db_column='Sales/Week', null=True)),
                ('item', models.CharField(blank=True, max_length=50, null=True)),
                ('pcs', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test1',
                'managed': False,
            },
        ),
    ]
